import './globals.css';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import { UserProvider } from '@/providers';
import { headers } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Chat App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {

  const getUser = async () => {
    const header = await headers();
    const user = header.get("x-user");
    if (user) {
      return JSON.parse(user);
    }

    return undefined;
  }

  const user = await getUser();
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-hidden`}>
        <UserProvider intialUser={user}>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
